version: 2
registries:
  wesjd-maven:
    type: maven-repository
    url: https://mvn.wesjd.net/

updates:
  - package-ecosystem: "gradle"
    directory: "/"

    registries:
      - wesjd-maven

    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Ho_Chi_Minh"

    allow:
      - dependency-name: "com.github.cryptomorin:XSeries"
      - dependency-name: "net.wesjd:anvilgui"

    commit-message:
      prefix: "libs"
      include: "scope"

    open-pull-requests-limit: 20
