name: Build MineVNLib
description: Set up Java and build MineVNLib JARs into target

runs:
  using: composite
  steps:
    - uses: ./.github/actions/setup-gradle
    - name: Build MineVNLib
      shell: bash
      run: |
        chmod +x ./gradlew
        ./gradlew assemble
        mkdir -p target
        cp ./minevnlib-plugin/build/libs/MineVNLib.jar ./target/MineVNLib.jar
        cp ./minevnlib-plugin/build/libs/MineVNLib-no-kotlin.jar ./target/MineVNLib-no-kotlin.jar
