name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - uses: gradle/actions/wrapper-validation@v6

      - uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 17
          cache: "gradle"

      - name: Build MineVNLib
        run: |
          chmod +x ./gradlew
          ./gradlew assemble
          mkdir -p target
          cp ./minevnlib-plugin/build/libs/MineVNLib.jar ./target/MineVNLib.jar
          cp ./minevnlib-plugin/build/libs/MineVNLib-no-kotlin.jar ./target/MineVNLib-no-kotlin.jar

      - name: Upload build artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: "MineVNLib"
          path: ./target/*.jar
