name: Build
on:
  workflow_dispatch:
  pull_request:
  push:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - name: Validate Gradle Wrapper checksum
        run: echo "7d3a4ac4de1c32b59bc6a4eb8ecb8e612ccd0cf1ae1e99f66902da64df296172  gradle/wrapper/gradle-wrapper.jar" | sha256sum --check
      - uses: actions/setup-java@v5.0.0
        with:
          distribution: temurin
          java-version: 25
          cache: "gradle"
      - name: Build MineVNLib & get plugin informations
        run: |
          chmod +x ./gradlew
          ./gradlew assemble
          mkdir -p target
          cp ./minevnlib-plugin/build/libs/MineVNLib.jar ./target/MineVNLib.jar
          cp ./minevnlib-plugin/build/libs/MineVNLib-no-kotlin.jar ./target/MineVNLib-no-kotlin.jar
          echo "hash=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          echo "version=$(./gradlew :minevnlib-plugin:printVersion | awk 'NR==3')" >> $GITHUB_OUTPUT
        id: plugin
      - name: Upload build artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: "MineVNLib"
          path: ./target/*.jar
      - name: Release
        if: github.ref_name == 'master'
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.plugin.outputs.version }}-${{ steps.plugin.outputs.hash }}
          prerelease: true
          name: "MineVNLib - ${{ steps.plugin.outputs.version }}-${{ steps.plugin.outputs.hash }}"
          artifacts: ./target/*.jar
          commit: master
