name: Upload JARs to Release
on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: ./.github/actions/build-minevnlib

      - name: Attach JARs to the Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./target/*.jar
